In [37]:
import pandas as pd

In [38]:
pd.set_option('display.max_columns', 3)

In [39]:
df = pd.read_csv(r'D:\Skills\NLP-Project-Collections\Gen Ai Project\News Research Tool\people_data.csv')

In [40]:
df

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo

In [41]:
from sentence_transformers import SentenceTransformer

In [42]:
encoder = SentenceTransformer('all-mpnet-base-v2')

In [43]:
vector = encoder.encode(df[['Name', 'Age', 'City']].astype(str).values.tolist())

In [44]:
vector

array([[ 0.03031487, -0.02608931,  0.00847733, ..., -0.00057782,
        -0.02771387,  0.00400893],
       [ 0.02054881, -0.01289909,  0.03084516, ..., -0.01530634,
        -0.03919758, -0.0019673 ],
       [ 0.00660378,  0.01011326,  0.00696509, ...,  0.01302526,
        -0.08549511,  0.01197167],
       [-0.01591302, -0.02891953,  0.00878875, ...,  0.00854507,
        -0.04582716, -0.01379935]], shape=(4, 768), dtype=float32)

In [45]:
vector.shape

(4, 768)

In [46]:
import faiss

In [47]:
dim = vector.shape[1]  # Get the dimension from the vector shape
index = faiss.IndexFlatL2(dim)

In [48]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001275325A0D0> >

In [49]:
index.add(vector)

In [64]:
search_data = ['Bob', '30', 'London']
search_vectors = encoder.encode([' '.join(search_data)])  # Join the items to match training data format
search_vector = search_vectors.reshape(1, -1)

In [65]:
search_vectors.shape

(1, 768)

In [66]:
search_vectors

array([[ 1.71638560e-02, -1.12210056e-02,  2.29080115e-02,
         9.80836339e-03, -1.43353110e-02,  2.44412711e-03,
         1.43321985e-02,  4.06643143e-03,  1.80241633e-02,
         8.95566016e-04,  3.54010500e-02, -3.57800201e-02,
        -9.09909140e-03,  1.71355321e-03, -7.88872782e-03,
        -8.17665607e-02, -1.12305616e-03, -3.31396656e-03,
        -7.76158040e-03, -9.80890449e-03, -3.61888856e-03,
         2.25472804e-02, -4.46158648e-02, -2.54396745e-03,
         1.83177944e-02,  4.64258716e-02, -2.11354364e-02,
         2.41296608e-02,  1.61304865e-02,  8.88763592e-02,
         1.30405342e-02,  6.24739658e-03,  7.39216525e-03,
        -1.05090057e-02,  1.76109154e-06,  2.81070918e-02,
        -7.79251568e-03, -1.28340237e-02,  4.08693822e-03,
        -2.24825256e-02, -6.27743229e-02,  6.53484017e-02,
        -4.07761782e-02,  5.45637012e-02, -3.42812836e-02,
        -4.27422747e-02,  3.64884399e-02, -1.98366717e-02,
         1.23766800e-02,  3.84314582e-02,  1.23109797e-0

In [67]:
import numpy as np
search_vectors = np.array(search_vectors).reshape(1, -1)  # Reshape to 2D array with one row
search_vectors.shape

(1, 768)

In [68]:
index.d

768

In [69]:
search_vectors.shape[1]

768

In [70]:
D, I = index.search(search_vectors.astype('float32'), k=2)

In [71]:
D

array([[0.5902074, 1.0169873]], dtype=float32)

In [73]:
I

array([[1, 0]])

In [77]:
df.iloc[[1,0]]

Name  Age      City
1    Bob   30    London
0  Alice   25  New York